import { Country } from "../types";

export const ALL_COUNTRIES: Country[] = [
  {
    id: "af",
    name: "Afghanistan",
    flag: "🇦🇫",
    population: 40000000,
    religion: "Islam",
    christianPercentage: 0.01,
    unreachedPercentage: 99.9,
    unreachedGroupsCount: 72,
    riskLevel: "Extreme",
    prayerPoints: ["Safety for underground believers.", "Digital scripture access.", "Peace and stability."],
    historicalContext: "Historically complex and currently very difficult for missions."
  },
  {
    id: "al",
    name: "Albania",
    flag: "🇦🇱",
    population: 2800000,
    religion: "Islam/Christianity",
    christianPercentage: 35,
    unreachedPercentage: 60,
    unreachedGroupsCount: 8,
    riskLevel: "Low",
    prayerPoints: ["Youth outreach.", "Church unity.", "Economic stability."],
    historicalContext: "A post-communist nation with growing religious freedom."
  },
  {
    id: "dz",
    name: "Algeria",
    flag: "🇩🇿",
    population: 44000000,
    religion: "Islam",
    christianPercentage: 0.3,
    unreachedPercentage: 98,
    unreachedGroupsCount: 35,
    riskLevel: "High",
    prayerPoints: ["Legal recognition for churches.", "Softening of hearts.", "Kabyle believers."],
    historicalContext: "North African nation with a small but vibrant church."
  },
  {
    id: "ad",
    name: "Andorra",
    flag: "🇦🇩",
    population: 77000,
    religion: "Christianity",
    christianPercentage: 89,
    unreachedPercentage: 10,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Spiritual awakening.", "Christian education.", "Community service."],
    historicalContext: "Small European principality with deep Christian roots."
  },
  {
    id: "ao",
    name: "Angola",
    flag: "🇦🇴",
    population: 33000000,
    religion: "Christianity",
    christianPercentage: 75,
    unreachedPercentage: 5,
    unreachedGroupsCount: 12,
    riskLevel: "Moderate",
    prayerPoints: ["Discipleship programs.", "Theological training.", "Reconciliation after war."],
    historicalContext: "Sub-Saharan nation recovering from long conflict."
  },
  {
    id: "ag",
    name: "Antigua and Barbuda",
    flag: "🇦🇬",
    population: 98000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 2,
    riskLevel: "Low",
    prayerPoints: ["Youth leadership.", "Family strength.", "Discipleship."],
    historicalContext: "Caribbean island nation with strong church presence."
  },
  {
    id: "ar",
    name: "Argentina",
    flag: "🇦🇷",
    population: 45000000,
    religion: "Christianity",
    christianPercentage: 85,
    unreachedPercentage: 10,
    unreachedGroupsCount: 15,
    riskLevel: "Low",
    prayerPoints: ["Church planting updates.", "Economic restoration.", "Unity among leaders."],
    historicalContext: "South American giant with a history of revival."
  },
  {
    id: "am",
    name: "Armenia",
    flag: "🇦🇲",
    population: 3000000,
    religion: "Christianity",
    christianPercentage: 94,
    unreachedPercentage: 5,
    unreachedGroupsCount: 4,
    riskLevel: "Moderate",
    prayerPoints: ["Stability in borders.", "Deeper spiritual devotion.", "Mercy for refugees."],
    historicalContext: "The first nation to adopt Christianity as a state religion."
  },
  {
    id: "au",
    name: "Australia",
    flag: "🇦🇺",
    population: 26000000,
    religion: "Christianity/Irreligious",
    christianPercentage: 45,
    unreachedPercentage: 20,
    unreachedGroupsCount: 30,
    riskLevel: "Low",
    prayerPoints: ["Indigenous ministry.", "Youth engagement.", "Counter-secularism."],
    historicalContext: "Multicultural nation with diverse mission needs."
  },
  {
    id: "at",
    name: "Austria",
    flag: "🇦🇹",
    population: 9000000,
    religion: "Christianity",
    christianPercentage: 70,
    unreachedPercentage: 15,
    unreachedGroupsCount: 10,
    riskLevel: "Low",
    prayerPoints: ["Revitalization of traditional churches.", "Migrant outreach.", "Student ministry."],
    historicalContext: "European nation with rich Catholic heritage."
  },
  {
    id: "az",
    name: "Azerbaijan",
    flag: "🇦🇿",
    population: 10000000,
    religion: "Islam",
    christianPercentage: 0.2,
    unreachedPercentage: 98,
    unreachedGroupsCount: 18,
    riskLevel: "High",
    prayerPoints: ["Religious freedom.", "Training for native leaders.", "Peace with neighbors."],
    historicalContext: "Caspian Sea nation with growing interest in the Gospel."
  },
  {
    id: "bs",
    name: "Bahamas",
    flag: "🇧🇸",
    population: 400000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 2,
    riskLevel: "Low",
    prayerPoints: ["Family values.", "Substance abuse recovery.", "Faithful witness."],
    historicalContext: "Archipelago with strong religious identity."
  },
  {
    id: "bh",
    name: "Bahrain",
    flag: "🇧🇭",
    population: 1700000,
    religion: "Islam",
    christianPercentage: 9,
    unreachedPercentage: 85,
    unreachedGroupsCount: 12,
    riskLevel: "Moderate",
    prayerPoints: ["Expatriate church safety.", "Local seekers.", "Dialogues."],
    historicalContext: "Gulf nation with a unique religious mix."
  },
  {
    id: "bd",
    name: "Bangladesh",
    flag: "🇧🇩",
    population: 165000000,
    religion: "Islam",
    christianPercentage: 0.5,
    unreachedPercentage: 98,
    unreachedGroupsCount: 380,
    riskLevel: "High",
    prayerPoints: ["The unreached Delta people.", "Disaster relief ministry.", "Protection for converts."],
    historicalContext: "Densely populated nation with mass unreached groups."
  },
  {
    id: "bb",
    name: "Barbados",
    flag: "🇧🇧",
    population: 290000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 2,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Revival among youth.", "Social justice.", "Evangelism."],
    historicalContext: "Stable Caribbean nation with deep Christian ties."
  },
  {
    id: "by",
    name: "Belarus",
    flag: "🇧🇾",
    population: 9400000,
    religion: "Christianity",
    christianPercentage: 60,
    unreachedPercentage: 10,
    unreachedGroupsCount: 5,
    riskLevel: "Moderate",
    prayerPoints: ["Freedom of assembly.", "Church unity.", "Economic hope."],
    historicalContext: "East European nation with resilient faith."
  },
  {
    id: "be",
    name: "Belgium",
    flag: "🇧🇪",
    population: 11500000,
    religion: "Christianity/Secular",
    christianPercentage: 50,
    unreachedPercentage: 30,
    unreachedGroupsCount: 25,
    riskLevel: "Low",
    prayerPoints: ["Relevance of the Gospel.", "Secularism challenge.", "Immigrant churches."],
    historicalContext: "European hub with significant spiritual drift."
  },
  {
    id: "bz",
    name: "Belize",
    flag: "🇧🇿",
    population: 400000,
    religion: "Christianity",
    christianPercentage: 70,
    unreachedPercentage: 5,
    unreachedGroupsCount: 4,
    riskLevel: "Low",
    prayerPoints: ["Drug addiction outreach.", "Biblical literacy.", "Unity."],
    historicalContext: "Central American nation with diverse ethnic groups."
  },
  {
    id: "bj",
    name: "Benin",
    flag: "🇧🇯",
    population: 12000000,
    religion: "Christianity/Voodoo",
    christianPercentage: 30,
    unreachedPercentage: 40,
    unreachedGroupsCount: 22,
    riskLevel: "Moderate",
    prayerPoints: ["Breakthrough in Voodoo Strongholds.", "Training pastors.", "Health initiatives."],
    historicalContext: "West African nation known as the cradle of Voodoo."
  },
  {
    id: "bt",
    name: "Bhutan",
    flag: "🇧🇹",
    population: 770000,
    religion: "Buddhism",
    christianPercentage: 0.5,
    unreachedPercentage: 99,
    unreachedGroupsCount: 24,
    riskLevel: "High",
    prayerPoints: ["Access for missionaries.", "Underground church growth.", "Tolerance."],
    historicalContext: "Himalayan kingdom where Christianity is restricted."
  },
  {
    id: "bo",
    name: "Bolivia",
    flag: "🇧🇴",
    population: 11600000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 12,
    riskLevel: "Moderate",
    prayerPoints: ["Indigenous outreach.", "Social equality.", "Discipleship."],
    historicalContext: "Andean nation with synchronized religious practices."
  },
  {
    id: "ba",
    name: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    population: 3300000,
    religion: "Islam/Christianity",
    christianPercentage: 50,
    unreachedPercentage: 45,
    unreachedGroupsCount: 6,
    riskLevel: "Moderate",
    prayerPoints: ["Healing from ethnic conflict.", "Youth vision.", "Transparency."],
    historicalContext: "Balkan nation with a history of religious divide."
  },
  {
    id: "bw",
    name: "Botswana",
    flag: "🇧🇼",
    population: 2300000,
    religion: "Christianity",
    christianPercentage: 75,
    unreachedPercentage: 5,
    unreachedGroupsCount: 4,
    riskLevel: "Low",
    prayerPoints: ["HIV/AIDS ministry.", "Spiritual maturity.", "Economic wisdom."],
    historicalContext: "Stable African democracy with high church attendance."
  },
  {
    id: "br",
    name: "Brazil",
    flag: "🇧🇷",
    population: 212000000,
    religion: "Christianity",
    christianPercentage: 85,
    unreachedPercentage: 5,
    unreachedGroupsCount: 45,
    riskLevel: "Low",
    prayerPoints: ["Amazon tribal groups.", "Urban violence solution.", "Sending capacity."],
    historicalContext: "Global powerhouse of Pentecostalism and missions."
  },
  {
    id: "bn",
    name: "Brunei",
    flag: "🇧🇳",
    population: 440000,
    religion: "Islam",
    christianPercentage: 10,
    unreachedPercentage: 85,
    unreachedGroupsCount: 8,
    riskLevel: "High",
    prayerPoints: ["Wisdom for believers.", "Bible translation access.", "Seekers."],
    historicalContext: "Wealthy Islamic sultanate in Southeast Asia."
  },
  {
    id: "bg",
    name: "Bulgaria",
    flag: "🇧🇬",
    population: 7000000,
    religion: "Christianity",
    christianPercentage: 80,
    unreachedPercentage: 15,
    unreachedGroupsCount: 15,
    riskLevel: "Low",
    prayerPoints: ["Roma community ministry.", "Revival in cities.", "Integrity."],
    historicalContext: "Balkan nation with ancient Orthodox roots."
  },
  {
    id: "bf",
    name: "Burkina Faso",
    flag: "🇧🇫",
    population: 21000000,
    religion: "Islam/Christianity",
    christianPercentage: 25,
    unreachedPercentage: 50,
    unreachedGroupsCount: 28,
    riskLevel: "Extreme",
    prayerPoints: ["Safety from insurgents.", "Food security.", "Unity among believers."],
    historicalContext: "Sahel nation facing significant security challenges."
  },
  {
    id: "bi",
    name: "Burundi",
    flag: "🇧🇮",
    population: 12000000,
    religion: "Christianity",
    christianPercentage: 85,
    unreachedPercentage: 2,
    unreachedGroupsCount: 3,
    riskLevel: "Moderate",
    prayerPoints: ["Reconciliation.", "Poverty alleviation.", "Christian education."],
    historicalContext: "Small, densely populated nation with high faith density."
  },
  {
    id: "kh",
    name: "Cambodia",
    flag: "🇰🇭",
    population: 16700000,
    religion: "Buddhism",
    christianPercentage: 1,
    unreachedPercentage: 98,
    unreachedGroupsCount: 35,
    riskLevel: "Moderate",
    prayerPoints: ["Healing from Khmer Rouge legacy.", "Village outreach.", "Bible schools."],
    historicalContext: "Southeast Asian nation rebuilding after genocide."
  },
  {
    id: "cm",
    name: "Cameroon",
    flag: "🇨🇲",
    population: 26000000,
    religion: "Christianity/Islam",
    christianPercentage: 65,
    unreachedPercentage: 20,
    unreachedGroupsCount: 45,
    riskLevel: "High",
    prayerPoints: ["Anglophone crisis peace.", "Northern outreach.", "Corruption help."],
    historicalContext: "Bilingual African nation with rich diversity."
  },
  {
    id: "ca",
    name: "Canada",
    flag: "🇨🇦",
    population: 38000000,
    religion: "Christianity/Secular",
    christianPercentage: 55,
    unreachedPercentage: 25,
    unreachedGroupsCount: 65,
    riskLevel: "Low",
    prayerPoints: ["First Nations ministry.", "Spiritual renewal.", "Ethnocultural churches."],
    historicalContext: "Vast multicultural nation with shifting spiritual landscape."
  },
  {
    id: "cv",
    name: "Cape Verde",
    flag: "🇨🇻",
    population: 550000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Youth exodus impact.", "Church leadership.", "Disciple-making."],
    historicalContext: "Island nation with Portuguese influences."
  },
  {
    id: "cf",
    name: "Central African Republic",
    flag: "🇨🇫",
    population: 4800000,
    religion: "Christianity/Islam",
    christianPercentage: 70,
    unreachedPercentage: 15,
    unreachedGroupsCount: 22,
    riskLevel: "Extreme",
    prayerPoints: ["Peace between militias.", "Refugee support.", "Trauma healing."],
    historicalContext: "Resource-rich but conflict-prone African nation."
  },
  {
    id: "td",
    name: "Chad",
    flag: "🇹🇩",
    population: 16000000,
    religion: "Islam/Christianity",
    christianPercentage: 35,
    unreachedPercentage: 60,
    unreachedGroupsCount: 75,
    riskLevel: "High",
    prayerPoints: ["Northern unreached reach.", "Leadership development.", "Water access."],
    historicalContext: "Sahelian nation with strategic importance."
  },
  {
    id: "cl",
    name: "Chile",
    flag: "🇨🇱",
    population: 19000000,
    religion: "Christianity",
    christianPercentage: 70,
    unreachedPercentage: 10,
    unreachedGroupsCount: 8,
    riskLevel: "Low",
    prayerPoints: ["Youth disillusionment.", "Social stability.", "Biblical integrity."],
    historicalContext: "South American nation with established evangelical presence."
  },
  {
    id: "cn",
    name: "China",
    flag: "🇨🇳",
    population: 1400000000,
    religion: "Irreligious/Buddhism",
    christianPercentage: 7,
    unreachedPercentage: 85,
    unreachedGroupsCount: 450,
    riskLevel: "High",
    prayerPoints: ["House church perseverance.", "Ethnic minorities (Uyghur, Tibet).", "Digital surveillance."],
    historicalContext: "Nation with explosive but sometimes suppressed church growth."
  },
  {
    id: "co",
    name: "Colombia",
    flag: "🇨🇴",
    population: 50000000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 15,
    riskLevel: "Moderate",
    prayerPoints: ["Peace process support.", "Rural believers' safety.", "Youth leadership."],
    historicalContext: "Nation overcoming decades of cartel and guerrilla violence."
  },
  {
    id: "km",
    name: "Comoros",
    flag: "🇰🇲",
    population: 870000,
    religion: "Islam",
    christianPercentage: 0.5,
    unreachedPercentage: 99,
    unreachedGroupsCount: 5,
    riskLevel: "High",
    prayerPoints: ["Protection for few believers.", "Openness to Gospel.", "Health aid."],
    historicalContext: "Islamic archipelago in the Indian Ocean."
  },
  {
    id: "cg",
    name: "Congo (Brazzaville)",
    flag: "🇨🇬",
    population: 5500000,
    religion: "Christianity",
    christianPercentage: 80,
    unreachedPercentage: 5,
    unreachedGroupsCount: 10,
    riskLevel: "Moderate",
    prayerPoints: ["Political reform.", "Discipleship.", "Health infrastructure."],
    historicalContext: "West African nation with strong Catholic and Protestant roots."
  },
  {
    id: "cd",
    name: "Congo (DRC)",
    flag: "🇨🇩",
    population: 90000000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 65,
    riskLevel: "Extreme",
    prayerPoints: ["Peace in Eastern DRC.", "Corruption fighting.", "Biblical training."],
    historicalContext: "Immense nation with huge resources and huge spiritual challenges."
  },
  {
    id: "cr",
    name: "Costa Rica",
    flag: "🇨🇷",
    population: 5000000,
    religion: "Christianity",
    christianPercentage: 85,
    unreachedPercentage: 5,
    unreachedGroupsCount: 3,
    riskLevel: "Low",
    prayerPoints: ["Missionary sending focus.", "Family strength.", "Social care."],
    historicalContext: "Peaceful Central American nation with strong missions focus."
  },
  {
    id: "ci",
    name: "Ivory Coast",
    flag: "🇨🇮",
    population: 26000000,
    religion: "Islam/Christianity",
    christianPercentage: 35,
    unreachedPercentage: 45,
    unreachedGroupsCount: 38,
    riskLevel: "Moderate",
    prayerPoints: ["Reconciliation since civil war.", "Northern groups reach.", "Integrity."],
    historicalContext: "West African hub for agriculture and trade."
  },
  {
    id: "hr",
    name: "Croatia",
    flag: "🇭🇷",
    population: 4000000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 5,
    riskLevel: "Low",
    prayerPoints: ["Spiritual depth.", "Youth reach.", "Ethnic reconciliation."],
    historicalContext: "Mediterranean nation with strong Catholic identity."
  },
  {
    id: "cu",
    name: "Cuba",
    flag: "🇨🇺",
    population: 11300000,
    religion: "Christianity/Irreligious",
    christianPercentage: 50,
    unreachedPercentage: 35,
    unreachedGroupsCount: 8,
    riskLevel: "Moderate",
    prayerPoints: ["House church movement.", "Economic freedom.", "Youth leadership."],
    historicalContext: "Island nation with a history of perseverance."
  },
  {
    id: "cy",
    name: "Cyprus",
    flag: "🇨🇾",
    population: 1200000,
    religion: "Christianity/Islam",
    christianPercentage: 73,
    unreachedPercentage: 20,
    unreachedGroupsCount: 7,
    riskLevel: "Low",
    prayerPoints: ["Reconciliation of divided island.", "Youth ministry.", "Disciple-making."],
    historicalContext: "Strategically located Mediterranean island."
  },
  {
    id: "cz",
    name: "Czechia",
    flag: "🇨🇿",
    population: 10700000,
    religion: "Irreligious",
    christianPercentage: 10,
    unreachedPercentage: 80,
    unreachedGroupsCount: 12,
    riskLevel: "Low",
    prayerPoints: ["Spiritual awakening in secular society.", "Youth reach.", "Bible study groups."],
    historicalContext: "One of the most atheistic nations in Europe."
  },
  {
    id: "dk",
    name: "Denmark",
    flag: "🇩🇰",
    population: 5800000,
    religion: "Christianity/Irreligious",
    christianPercentage: 75,
    unreachedPercentage: 20,
    unreachedGroupsCount: 15,
    riskLevel: "Low",
    prayerPoints: ["Faith in a secular age.", "Migrant outreach.", "Mental health ministry."],
    historicalContext: "Nordic nation with Lutheran state church roots."
  },
  {
    id: "dj",
    name: "Djibouti",
    flag: "🇩🇯",
    population: 980000,
    religion: "Islam",
    christianPercentage: 1.5,
    unreachedPercentage: 98,
    unreachedGroupsCount: 6,
    riskLevel: "High",
    prayerPoints: ["Seeking souls among Afar/Somali.", "Aviation missions.", "Water aid."],
    historicalContext: "Strategic gateway to East Africa."
  },
  {
    id: "dm",
    name: "Dominica",
    flag: "🇩🇲",
    population: 72000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Disaster resilience.", "Youth leadership.", "Family unity."],
    historicalContext: "Caribbean island nation with vibrant faith."
  },
  {
    id: "ec",
    name: "Ecuador",
    flag: "🇪🇨",
    population: 17600000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 15,
    riskLevel: "Moderate",
    prayerPoints: ["Indigenous Amazonian groups.", "Youth outreach.", "Social justice."],
    historicalContext: "Equatorial nation with strong highland and jungle cultures."
  },
  {
    id: "eg",
    name: "Egypt",
    flag: "🇪🇬",
    population: 102000000,
    religion: "Islam",
    christianPercentage: 10,
    unreachedPercentage: 85,
    unreachedGroupsCount: 45,
    riskLevel: "High",
    prayerPoints: ["Protection for Coptic believers.", "Seekers in major cities.", "Bible SOCIETY work."],
    historicalContext: "Ancient civilization with one of the oldest Christian communities."
  },
  {
    id: "sv",
    name: "El Salvador",
    flag: "🇸🇻",
    population: 6500000,
    religion: "Christianity",
    christianPercentage: 85,
    unreachedPercentage: 5,
    unreachedGroupsCount: 2,
    riskLevel: "Moderate",
    prayerPoints: ["Gang rehabilitation ministry.", "Family healing.", "Economic hope."],
    historicalContext: "Central American nation overcoming gang violence."
  },
  {
    id: "gq",
    name: "Equatorial Guinea",
    flag: "🇬🇶",
    population: 1400000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 4,
    riskLevel: "Moderate",
    prayerPoints: ["Training native leaders.", "Openness to Gospel.", "Poverty aid."],
    historicalContext: "Spanish-speaking African nation with oil wealth."
  },
  {
    id: "er",
    name: "Eritrea",
    flag: "🇪🇷",
    population: 3500000,
    religion: "Christianity/Islam",
    christianPercentage: 50,
    unreachedPercentage: 48,
    unreachedGroupsCount: 14,
    riskLevel: "Extreme",
    prayerPoints: ["Persecuted house church leaders.", "Refugee seekers.", "Legal recognition."],
    historicalContext: "Red Sea nation known as the 'North Korea of Africa' for believers."
  },
  {
    id: "ee",
    name: "Estonia",
    flag: "🇪🇪",
    population: 1300000,
    religion: "Irreligious",
    christianPercentage: 20,
    unreachedPercentage: 75,
    unreachedGroupsCount: 6,
    riskLevel: "Low",
    prayerPoints: ["Spiritual awakening.", "Youth digital outreach.", "Church relevance."],
    historicalContext: "Highly secularized Baltic nation."
  },
  {
    id: "sz",
    name: "Eswatini",
    flag: "🇸🇿",
    population: 1100000,
    religion: "Christianity",
    christianPercentage: 80,
    unreachedPercentage: 5,
    unreachedGroupsCount: 3,
    riskLevel: "Moderate",
    prayerPoints: ["HIV/AIDS support.", "Family values.", "Youth vision."],
    historicalContext: "Monarchy in Southern Africa with high faith engagement."
  },
  {
    id: "et",
    name: "Ethiopia",
    flag: "🇪🇹",
    population: 115000000,
    religion: "Christianity/Islam",
    christianPercentage: 60,
    unreachedPercentage: 35,
    unreachedGroupsCount: 38,
    riskLevel: "High",
    prayerPoints: ["Peace between ethnic groups.", "Deeper spiritual devotion.", "Missionaries being sent out."],
    historicalContext: "Nation with ancient Christian heritage and fast-growing evangelicalism."
  },
  {
    id: "fj",
    name: "Fiji",
    flag: "🇫🇯",
    population: 890000,
    religion: "Christianity/Hinduism",
    christianPercentage: 65,
    unreachedPercentage: 30,
    unreachedGroupsCount: 8,
    riskLevel: "Low",
    prayerPoints: ["Reaching Indo-Fijians.", "Leadership training.", "Environmental care."],
    historicalContext: "Melanesian nation with strong Methodist roots."
  },
  {
    id: "fi",
    name: "Finland",
    flag: "🇫🇮",
    population: 5500000,
    religion: "Christianity/Irreligious",
    christianPercentage: 70,
    unreachedPercentage: 25,
    unreachedGroupsCount: 12,
    riskLevel: "Low",
    prayerPoints: ["Personal faith versus cultural religion.", "Mental wellness.", "Immigrant work."],
    historicalContext: "Nordic nation with deep Lutheran history."
  },
  {
    id: "fr",
    name: "France",
    flag: "🇫🇷",
    population: 67000000,
    religion: "Christianity/Irreligious",
    christianPercentage: 51,
    unreachedPercentage: 45,
    unreachedGroupsCount: 85,
    riskLevel: "Low",
    prayerPoints: ["Revival in Paris and beyond.", "Muslim migrant outreach.", "University missions."],
    historicalContext: "West European powerhouse with complex secular identity (Laïcité)."
  },
  {
    id: "ga",
    name: "Gabon",
    flag: "🇬🇦",
    population: 2200000,
    religion: "Christianity",
    christianPercentage: 75,
    unreachedPercentage: 10,
    unreachedGroupsCount: 8,
    riskLevel: "Moderate",
    prayerPoints: ["Integrity in government.", "Village outreach.", "Family strength."],
    historicalContext: "Central African nation with rich natural preserves."
  },
  {
    id: "gm",
    name: "Gambia",
    flag: "🇬🇲",
    population: 2400000,
    religion: "Islam",
    christianPercentage: 4,
    unreachedPercentage: 95,
    unreachedGroupsCount: 12,
    riskLevel: "Moderate",
    prayerPoints: ["Freedom to share Gospel.", "Bible translation projects.", "Education for youth."],
    historicalContext: "Small West African river nation."
  },
  {
    id: "ge",
    name: "Georgia",
    flag: "🇬🇪",
    population: 3700000,
    religion: "Christianity",
    christianPercentage: 85,
    unreachedPercentage: 10,
    unreachedGroupsCount: 10,
    riskLevel: "Moderate",
    prayerPoints: ["Inner transformation through faith.", "Yezidi outreach.", "Peace with Russia."],
    historicalContext: "Caucasus nation with ancient Orthodox identity."
  },
  {
    id: "de",
    name: "Germany",
    flag: "🇩🇪",
    population: 83000000,
    religion: "Christianity/Irreligious",
    christianPercentage: 55,
    unreachedPercentage: 40,
    unreachedGroupsCount: 75,
    riskLevel: "Low",
    prayerPoints: ["Re-evangelizing the North.", "Migrant inclusion.", "Theological integrity."],
    historicalContext: "The birthplace of the Protestant Reformation."
  },
  {
    id: "gh",
    name: "Ghana",
    flag: "🇬🇭",
    population: 31000000,
    religion: "Christianity",
    christianPercentage: 70,
    unreachedPercentage: 15,
    unreachedGroupsCount: 22,
    riskLevel: "Low",
    prayerPoints: ["Sending missionaries to Sahel.", "Biblical discipleship.", "Transparency."],
    historicalContext: "West African hub for missionary training and sending."
  },
  {
    id: "gr",
    name: "Greece",
    flag: "🇬🇷",
    population: 10500000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 10,
    unreachedGroupsCount: 12,
    riskLevel: "Low",
    prayerPoints: ["Personal spiritual renewal.", "Refugee ministry hub.", "Youth outreach."],
    historicalContext: "Biblical region where Paul the Apostle once preached."
  },
  {
    id: "gd",
    name: "Grenada",
    flag: "🇬🇩",
    population: 112000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 5,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Vibrant testimony.", "Family stability.", "Educational and spiritual growth."],
    historicalContext: "Caribbean 'Spice Island' with strong faith culture."
  },
  {
    id: "gt",
    name: "Guatemala",
    flag: "🇬🇹",
    population: 18000000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 15,
    riskLevel: "Moderate",
    prayerPoints: ["Growth in integrity.", "Mayan village outreach.", "Child health."],
    historicalContext: "Central American nation with significant Pentecostal growth."
  },
  {
    id: "gn",
    name: "Guinea",
    flag: "🇬🇳",
    population: 13000000,
    religion: "Islam",
    christianPercentage: 5,
    unreachedPercentage: 90,
    unreachedGroupsCount: 40,
    riskLevel: "High",
    prayerPoints: ["Access to unreached areas.", "Medical missions impact.", "Freedom."],
    historicalContext: "West African nation with significant mineral resources."
  },
  {
    id: "gw",
    name: "Guinea-Bissau",
    flag: "🇬🇼",
    population: 2000000,
    religion: "Islam/Christianity",
    christianPercentage: 15,
    unreachedPercentage: 50,
    unreachedGroupsCount: 15,
    riskLevel: "High",
    prayerPoints: ["Political stability.", "Church planting focus.", "Water systems."],
    historicalContext: "Small West African nation with history of instability."
  },
  {
    id: "gy",
    name: "Guyana",
    flag: "🇬🇾",
    population: 780000,
    religion: "Christianity/Hinduism",
    christianPercentage: 60,
    unreachedPercentage: 35,
    unreachedGroupsCount: 6,
    riskLevel: "Low",
    prayerPoints: ["Unity in diversity.", "Interior tribes reach.", "Youth vision."],
    historicalContext: "English-speaking South American nation with Caribbean ties."
  },
  {
    id: "ht",
    name: "Haiti",
    flag: "🇭🇹",
    population: 11400000,
    religion: "Christianity/Voodoo",
    christianPercentage: 80,
    unreachedPercentage: 15,
    unreachedGroupsCount: 8,
    riskLevel: "Extreme",
    prayerPoints: ["Restoration from gang chaos.", "Biblical depth vs Syncretism.", "Child protection."],
    historicalContext: "The first free black republic, facing ongoing spiritual and physical battles."
  },
  {
    id: "hn",
    name: "Honduras",
    flag: "🇭🇳",
    population: 9900000,
    religion: "Christianity",
    christianPercentage: 85,
    unreachedPercentage: 5,
    unreachedGroupsCount: 6,
    riskLevel: "Moderate",
    prayerPoints: ["Corruption help.", "Youth resilience.", "Evangelism in mountains."],
    historicalContext: "Central American nation known for coffee and complex politics."
  },
  {
    id: "hu",
    name: "Hungary",
    flag: "🇭🇺",
    population: 9600000,
    religion: "Christianity",
    christianPercentage: 70,
    unreachedPercentage: 25,
    unreachedGroupsCount: 12,
    riskLevel: "Low",
    prayerPoints: ["Awakening in youth.", "Disciple-making chains.", "Roma ministry."],
    historicalContext: "Central European nation with a history of intellectual and religious pride."
  },
  {
    id: "is",
    name: "Iceland",
    flag: "🇮🇸",
    population: 360000,
    religion: "Christianity/Irreligious",
    christianPercentage: 70,
    unreachedPercentage: 25,
    unreachedGroupsCount: 4,
    riskLevel: "Low",
    prayerPoints: ["Gospel relevance.", "Spiritual hunger.", "Isolation relief."],
    historicalContext: "Isolated Arctic nation with strong cultural religion."
  },
  {
    id: "in",
    name: "India",
    flag: "🇮🇳",
    population: 1400000000,
    religion: "Hinduism",
    christianPercentage: 2.3,
    unreachedPercentage: 95,
    unreachedGroupsCount: 2135,
    riskLevel: "High",
    prayerPoints: ["Revival among unreached castes.", "Village outreach.", "Protection from persecution."],
    historicalContext: "Vast democracy with the world's largest concentration of unreached people."
  },
  {
    id: "id",
    name: "Indonesia",
    flag: "🇮🇩",
    population: 273000000,
    religion: "Islam",
    christianPercentage: 10,
    unreachedPercentage: 85,
    unreachedGroupsCount: 230,
    riskLevel: "Moderate",
    prayerPoints: ["Island-by-island breakthrough.", "Seeking souls in Java.", "Peace."],
    historicalContext: "Archipelago nation with the world's largest Muslim population."
  },
  {
    id: "ir",
    name: "Iran",
    flag: "🇮🇷",
    population: 84000000,
    religion: "Islam",
    christianPercentage: 1,
    unreachedPercentage: 98,
    unreachedGroupsCount: 85,
    riskLevel: "Extreme",
    prayerPoints: ["House church explosion.", "Seekers' dreams/visions.", "Freedom for prisoners."],
    historicalContext: "Home to the fastest-growing underground church in the world."
  },
  {
    id: "iq",
    name: "Iraq",
    flag: "🇮🇶",
    population: 40000000,
    religion: "Islam",
    christianPercentage: 1,
    unreachedPercentage: 98,
    unreachedGroupsCount: 35,
    riskLevel: "Extreme",
    prayerPoints: ["Return of displaced believers.", "Healing from ISIS impact.", "Kurdish outreach."],
    historicalContext: "Biblical region with modern hardships and growing openness in some areas."
  },
  {
    id: "ie",
    name: "Ireland",
    flag: "🇮🇪",
    population: 4900000,
    religion: "Christianity",
    christianPercentage: 80,
    unreachedPercentage: 15,
    unreachedGroupsCount: 8,
    riskLevel: "Low",
    prayerPoints: ["Gospel rediscovery.", "Forgiveness for church scandals.", "Youth passion."],
    historicalContext: "The 'Island of Saints and Scholars' now facing secularism."
  },
  {
    id: "il",
    name: "Israel",
    flag: "🇮🇱",
    population: 9200000,
    religion: "Judaism",
    christianPercentage: 2,
    unreachedPercentage: 90,
    unreachedGroupsCount: 15,
    riskLevel: "High",
    prayerPoints: ["Peace of Jerusalem.", "Messianic body growth.", "Arab/Jew reconciliation."],
    historicalContext: "Holy Land with unique spiritual and political complexities."
  },
  {
    id: "it",
    name: "Italy",
    flag: "🇮🇹",
    population: 60000000,
    religion: "Christianity",
    christianPercentage: 80,
    unreachedPercentage: 15,
    unreachedGroupsCount: 25,
    riskLevel: "Low",
    prayerPoints: ["Revival in religious structures.", "Migrant outreach.", "Secular youth."],
    historicalContext: "Catholic global center with needs for vibrant evangelical witness."
  },
  {
    id: "jm",
    name: "Jamaica",
    flag: "🇯🇲",
    population: 3000000,
    religion: "Christianity",
    christianPercentage: 70,
    unreachedPercentage: 5,
    unreachedGroupsCount: 2,
    riskLevel: "Low",
    prayerPoints: ["Ending violence.", "Family restoration.", "Youth mission zeal."],
    historicalContext: "Island with major cultural and spiritual influence globally."
  },
  {
    id: "jp",
    name: "Japan",
    flag: "🇯🇵",
    population: 126000000,
    religion: "Shintoism/Buddhism",
    christianPercentage: 1,
    unreachedPercentage: 98,
    unreachedGroupsCount: 95,
    riskLevel: "Low",
    prayerPoints: ["Spiritual awakening among youth.", "Breaking through work-culture.", "Hope."],
    historicalContext: "The 'Missionary Graveyard' now seeing new seeds being sown."
  },
  {
    id: "jo",
    name: "Jordan",
    flag: "🇯🇴",
    population: 10000000,
    religion: "Islam",
    christianPercentage: 2,
    unreachedPercentage: 95,
    unreachedGroupsCount: 18,
    riskLevel: "Moderate",
    prayerPoints: ["Refugee ministry.", "King's wisdom.", "Quiet seekers."],
    historicalContext: "Middle Eastern oasis of relative stability and refugee care."
  },
  {
    id: "kz",
    name: "Kazakhstan",
    flag: "🇰🇿",
    population: 19000000,
    religion: "Islam",
    christianPercentage: 15,
    unreachedPercentage: 70,
    unreachedGroupsCount: 45,
    riskLevel: "Moderate",
    prayerPoints: ["Evangelism among locals.", "Legal status for churches.", "Youth vision."],
    historicalContext: "Central Asian giant with significant Russian and native populations."
  },
  {
    id: "ke",
    name: "Kenya",
    flag: "🇰🇪",
    population: 53000000,
    religion: "Christianity",
    christianPercentage: 80,
    unreachedPercentage: 15,
    unreachedGroupsCount: 35,
    riskLevel: "High",
    prayerPoints: ["Northern frontier reach.", "Integrative discipleship.", "Youth in cities."],
    historicalContext: "East African hub for mission sending and training."
  },
  {
    id: "ki",
    name: "Kiribati",
    flag: "🇰🇮",
    population: 120000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Climate resilience.", "Theological depth.", "Community unity."],
    historicalContext: "Remote Pacific island nation."
  },
  {
    id: "kp",
    name: "North Korea",
    flag: "🇰🇵",
    population: 25800000,
    religion: "Atheism/Juche",
    christianPercentage: 1,
    unreachedPercentage: 99,
    unreachedGroupsCount: 5,
    riskLevel: "Extreme",
    prayerPoints: ["Freedom for underground believers.", "End of famine.", "Gospel opening."],
    historicalContext: "The most difficult place in the world for Christians."
  },
  {
    id: "kr",
    name: "South Korea",
    flag: "🇰🇷",
    population: 51700000,
    religion: "Christianity/Buddhism",
    christianPercentage: 30,
    unreachedPercentage: 30,
    unreachedGroupsCount: 12,
    riskLevel: "Low",
    prayerPoints: ["Missionary sending focus.", "Revitalizing youth passion.", "Reunification."],
    historicalContext: "Modern powerhouse of global missionary sending."
  },
  {
    id: "kw",
    name: "Kuwait",
    flag: "🇰🇼",
    population: 4300000,
    religion: "Islam",
    christianPercentage: 15,
    unreachedPercentage: 75,
    unreachedGroupsCount: 14,
    riskLevel: "Moderate",
    prayerPoints: ["Seekers in local families.", "Expat church maturity.", "Stability."],
    historicalContext: "Gulf nation with large expatriate Christian population."
  },
  {
    id: "kg",
    name: "Kyrgyzstan",
    flag: "🇰🇬",
    population: 6600000,
    religion: "Islam",
    christianPercentage: 5,
    unreachedPercentage: 85,
    unreachedGroupsCount: 28,
    riskLevel: "Moderate",
    prayerPoints: ["Training local leaders.", "Villages access.", "Unity."],
    historicalContext: "Mountainous Central Asian nation with vibrant small churches."
  },
  {
    id: "la",
    name: "Laos",
    flag: "🇱🇦",
    population: 7300000,
    religion: "Buddhism",
    christianPercentage: 2,
    unreachedPercentage: 95,
    unreachedGroupsCount: 120,
    riskLevel: "High",
    prayerPoints: ["Freedom for house churches.", "Village outreach.", "Bible translation."],
    historicalContext: "Communist nation with strict religious controls."
  },
  {
    id: "lv",
    name: "Latvia",
    flag: "🇱🇻",
    population: 1900000,
    religion: "Christianity",
    christianPercentage: 65,
    unreachedPercentage: 10,
    unreachedGroupsCount: 5,
    riskLevel: "Low",
    prayerPoints: ["Unity among denominations.", "Youth reach.", "Social justice."],
    historicalContext: "Baltic nation with Lutheran and Catholic roots."
  },
  {
    id: "lb",
    name: "Lebanon",
    flag: "🇱🇧",
    population: 6800000,
    religion: "Islam/Christianity",
    christianPercentage: 35,
    unreachedPercentage: 60,
    unreachedGroupsCount: 18,
    riskLevel: "High",
    prayerPoints: ["Peace and economic restoration.", "Refugee seekers.", "Church unity."],
    historicalContext: "Middle Eastern gateway with significant historical Christian presence."
  },
  {
    id: "ls",
    name: "Lesotho",
    flag: "🇱🇸",
    population: 2100000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 4,
    riskLevel: "Low",
    prayerPoints: ["Basotho shepherds outreach.", "HIV/AIDS healing.", "Integrity."],
    historicalContext: "High-altitude kingdom surrounded by South Africa."
  },
  {
    id: "lr",
    name: "Liberia",
    flag: "🇱🇷",
    population: 5000000,
    religion: "Christianity",
    christianPercentage: 80,
    unreachedPercentage: 15,
    unreachedGroupsCount: 12,
    riskLevel: "Moderate",
    prayerPoints: ["Recovery from history of war.", "Corruption help.", "Discipleship."],
    historicalContext: "West African nation founded by free slaves."
  },
  {
    id: "li",
    name: "Liechtenstein",
    flag: "🇱🇮",
    population: 38000,
    religion: "Christianity",
    christianPercentage: 80,
    unreachedPercentage: 10,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Spiritual hunger.", "Christian influence in finance.", "Community."],
    historicalContext: "Small Alpine principality."
  },
  {
    id: "lt",
    name: "Lithuania",
    flag: "🇱🇹",
    population: 2800000,
    religion: "Christianity",
    christianPercentage: 80,
    unreachedPercentage: 10,
    unreachedGroupsCount: 5,
    riskLevel: "Low",
    prayerPoints: ["Youth revival.", "Church collaboration.", "Integrity."],
    historicalContext: "Baltic nation with strong Catholic identity."
  },
  {
    id: "lu",
    name: "Luxembourg",
    flag: "🇱🇺",
    population: 630000,
    religion: "Christianity",
    christianPercentage: 70,
    unreachedPercentage: 20,
    unreachedGroupsCount: 8,
    riskLevel: "Low",
    prayerPoints: ["Secularism challenge.", "Expat spiritual needs.", "Church health."],
    historicalContext: "Wealthy European hub."
  },
  {
    id: "mg",
    name: "Madagascar",
    flag: "🇲🇬",
    population: 27700000,
    religion: "Christianity/Indigenous",
    christianPercentage: 45,
    unreachedPercentage: 15,
    unreachedGroupsCount: 12,
    riskLevel: "Moderate",
    prayerPoints: ["Rural village outreach.", "Bibles in local dialects.", "Economic hope."],
    historicalContext: "Island nation with unique biodiversity and spiritual mix."
  },
  {
    id: "mw",
    name: "Malawi",
    flag: "🇲🇼",
    population: 19000000,
    religion: "Christianity/Islam",
    christianPercentage: 80,
    unreachedPercentage: 15,
    unreachedGroupsCount: 15,
    riskLevel: "Moderate",
    prayerPoints: ["Muslim Yao outreach.", "Health initiatives.", "Deepening discipleship."],
    historicalContext: "Known as the 'Warm Heart of Africa'."
  },
  {
    id: "my",
    name: "Malaysia",
    flag: "🇲🇾",
    population: 32000000,
    religion: "Islam",
    christianPercentage: 9,
    unreachedPercentage: 60,
    unreachedGroupsCount: 165,
    riskLevel: "Moderate",
    prayerPoints: ["Freedom for Malays.", "East Malaysia indigenous growth.", "Unity."],
    historicalContext: "Multi-ethnic nation with state-enforced religious structures."
  },
  {
    id: "mv",
    name: "Maldives",
    flag: "🇲🇻",
    population: 540000,
    religion: "Islam",
    christianPercentage: 0.1,
    unreachedPercentage: 99.9,
    unreachedGroupsCount: 2,
    riskLevel: "Extreme",
    prayerPoints: ["Underground church safety.", "Freedom to believe.", "Visitors' influence."],
    historicalContext: "Tourism-heavy archipelago with total Islamic control."
  },
  {
    id: "ml",
    name: "Mali",
    flag: "🇲🇱",
    population: 20000000,
    religion: "Islam",
    christianPercentage: 2,
    unreachedPercentage: 90,
    unreachedGroupsCount: 45,
    riskLevel: "Extreme",
    prayerPoints: ["Safety from jihadi groups.", "Humanitarian aid.", "Openness in Timbuktu area."],
    historicalContext: "Sahel nation with ancient Islamic learning centers."
  },
  {
    id: "mt",
    name: "Malta",
    flag: "🇲🇹",
    population: 515000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 5,
    unreachedGroupsCount: 2,
    riskLevel: "Low",
    prayerPoints: ["Vibrant faith.", "Refugee welcoming spirit.", "Youth."],
    historicalContext: "Mediterranean island where Paul was shipwrecked."
  },
  {
    id: "mh",
    name: "Marshall Islands",
    flag: "🇲🇭",
    population: 59000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 2,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Spiritual depth.", "Social resilience.", "Educational growth."],
    historicalContext: "Pacific nation with strong Protestant history."
  },
  {
    id: "mr",
    name: "Mauritania",
    flag: "🇲🇷",
    population: 4600000,
    religion: "Islam",
    christianPercentage: 0.1,
    unreachedPercentage: 99.9,
    unreachedGroupsCount: 10,
    riskLevel: "Extreme",
    prayerPoints: ["Access to nomads.", "Freedom for few converts.", "End of slavery."],
    historicalContext: "Totalitarian Islamic republic in the Sahara."
  },
  {
    id: "mu",
    name: "Mauritius",
    flag: "🇲🇺",
    population: 1270000,
    religion: "Hinduism/Christianity",
    christianPercentage: 30,
    unreachedPercentage: 50,
    unreachedGroupsCount: 5,
    riskLevel: "Low",
    prayerPoints: ["Hindu outreach.", "Unity in diverse church.", "Youth values."],
    historicalContext: "Highly diverse Indian Ocean island."
  },
  {
    id: "mx",
    name: "Mexico",
    flag: "🇲🇽",
    population: 128000000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 65,
    riskLevel: "Moderate",
    prayerPoints: ["Indigenous groups in Chiapas.", "Protection from cartel violence.", "Urban revival."],
    historicalContext: "Major North American nation with complex Catholic and Evangelical history."
  },
  {
    id: "fm",
    name: "Micronesia",
    flag: "🇫🇲",
    population: 115000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 2,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Biblical literacy.", "Family strength.", "Social unity."],
    historicalContext: "Archipelago in Oceania."
  },
  {
    id: "md",
    name: "Moldova",
    flag: "🇲🇩",
    population: 2600000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 4,
    riskLevel: "Moderate",
    prayerPoints: ["Economic hope.", "Church mission zeal.", "Integrity."],
    historicalContext: "Post-Soviet nation with a very strong evangelical minority."
  },
  {
    id: "mc",
    name: "Monaco",
    flag: "🇲🇨",
    population: 39000,
    religion: "Christianity",
    christianPercentage: 80,
    unreachedPercentage: 15,
    unreachedGroupsCount: 2,
    riskLevel: "Low",
    prayerPoints: ["Seeking God over wealth.", "Authentic discipleship.", "Outreach."],
    historicalContext: "Smallest affluent principality."
  },
  {
    id: "mn",
    name: "Mongolia",
    flag: "🇲🇳",
    population: 3300000,
    religion: "Buddhism/Shamanism",
    christianPercentage: 1.5,
    unreachedPercentage: 95,
    unreachedGroupsCount: 22,
    riskLevel: "Low",
    prayerPoints: ["Nomadic tribes outreach.", "First-generation leaders.", "Unity."],
    historicalContext: "Nation that saw massive church growth in the 1990s."
  },
  {
    id: "me",
    name: "Montenegro",
    flag: "🇲🇪",
    population: 620000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 10,
    unreachedGroupsCount: 3,
    riskLevel: "Low",
    prayerPoints: ["Spiritual depth.", "Youth focus.", "Reconciliation."],
    historicalContext: "Balkan nation with scenic mountains and ancient roots."
  },
  {
    id: "ma",
    name: "Morocco",
    flag: "🇲🇦",
    population: 37000000,
    religion: "Islam",
    christianPercentage: 0.1,
    unreachedPercentage: 99.8,
    unreachedGroupsCount: 35,
    riskLevel: "High",
    prayerPoints: ["Freedom for Berber seekers.", "Safety for home groups.", "Social aid."],
    historicalContext: "Western North African kingdom with rich cultural history."
  },
  {
    id: "mz",
    name: "Mozambique",
    flag: "🇲🇿",
    population: 31000000,
    religion: "Christianity/Islam",
    christianPercentage: 55,
    unreachedPercentage: 25,
    unreachedGroupsCount: 38,
    riskLevel: "High",
    prayerPoints: ["Safety in Cabo Delgado.", "Flood relief ministry.", "Training pastors."],
    historicalContext: "Portuguese-speaking African nation with explosive revival in some areas."
  },
  {
    id: "mm",
    name: "Myanmar",
    flag: "🇲🇲",
    population: 54000000,
    religion: "Buddhism",
    christianPercentage: 6,
    unreachedPercentage: 90,
    unreachedGroupsCount: 75,
    riskLevel: "Extreme",
    prayerPoints: ["Peace in conflict zones.", "Ethnic minority churches.", "Humanitarian help."],
    historicalContext: "Strategically located nation with long-standing internal conflicts."
  },
  {
    id: "na",
    name: "Namibia",
    flag: "🇳🇦",
    population: 2500000,
    religion: "Christianity",
    christianPercentage: 85,
    unreachedPercentage: 10,
    unreachedGroupsCount: 12,
    riskLevel: "Low",
    prayerPoints: ["Bushmen (San) outreach.", "HIV focus.", "Youth leadership."],
    historicalContext: "Densely dry but spiritually active desert nation."
  },
  {
    id: "nr",
    name: "Nauru",
    flag: "🇳🇷",
    population: 10000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 2,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Health and spirit.", "Environment.", "Youth."],
    historicalContext: "Smallest island nation in Oceania."
  },
  {
    id: "np",
    name: "Nepal",
    flag: "🇳🇵",
    population: 29000000,
    religion: "Hinduism",
    christianPercentage: 1.5,
    unreachedPercentage: 97,
    unreachedGroupsCount: 250,
    riskLevel: "High",
    prayerPoints: ["Mountain village access.", "Training for first-gen leaders.", "Freedom."],
    historicalContext: "Former Hindu kingdom seeing recent significant church growth."
  },
  {
    id: "nl",
    name: "Netherlands",
    flag: "🇳🇱",
    population: 17500000,
    religion: "Irreligious/Christianity",
    christianPercentage: 40,
    unreachedPercentage: 55,
    unreachedGroupsCount: 22,
    riskLevel: "Low",
    prayerPoints: ["Secular target groups.", "Modern mission models.", "Immigrant churches."],
    historicalContext: "Nation with ancient Reformed tradition now deeply secular."
  },
  {
    id: "nz",
    name: "New Zealand",
    flag: "🇳🇿",
    population: 5000000,
    religion: "Irreligious/Christianity",
    christianPercentage: 40,
    unreachedPercentage: 50,
    unreachedGroupsCount: 12,
    riskLevel: "Low",
    prayerPoints: ["Maori ministry.", "Countering secularization.", "Family strength."],
    historicalContext: "Pacific nation with strong indigenous roots."
  },
  {
    id: "ni",
    name: "Nicaragua",
    flag: "🇳🇮",
    population: 6600000,
    religion: "Christianity",
    christianPercentage: 85,
    unreachedPercentage: 5,
    unreachedGroupsCount: 10,
    riskLevel: "High",
    prayerPoints: ["Freedom for churches.", "Social justice.", "Poverty alleviation."],
    historicalContext: "Central American nation facing political pressure on believers."
  },
  {
    id: "ne",
    name: "Niger",
    flag: "🇳🇪",
    population: 24000000,
    religion: "Islam",
    christianPercentage: 0.5,
    unreachedPercentage: 99,
    unreachedGroupsCount: 35,
    riskLevel: "Extreme",
    prayerPoints: ["Sahel security.", "Desert nomad seekers.", "NGO mission work."],
    historicalContext: "One of the world's most unreached and impoverished nations."
  },
  {
    id: "ng",
    name: "Nigeria",
    flag: "🇳🇬",
    population: 206000000,
    religion: "Christianity/Islam",
    christianPercentage: 45,
    unreachedPercentage: 50,
    unreachedGroupsCount: 95,
    riskLevel: "Extreme",
    prayerPoints: ["Northern persecuted church.", "Tackling corruption.", "Sending 100k missionaries."],
    historicalContext: "The 'Giant of Africa' with a major spiritual divide between north and south."
  },
  {
    id: "mk",
    name: "North Macedonia",
    flag: "🇲🇰",
    population: 2100000,
    religion: "Christianity/Islam",
    christianPercentage: 65,
    unreachedPercentage: 30,
    unreachedGroupsCount: 8,
    riskLevel: "Low",
    prayerPoints: ["Inter-ethnic peace.", "Youth awakening.", "Integrity."],
    historicalContext: "Balkan nation with complex regional identity."
  },
  {
    id: "no",
    name: "Norway",
    flag: "🇳🇴",
    population: 5400000,
    religion: "Christianity/Irreligious",
    christianPercentage: 70,
    unreachedPercentage: 25,
    unreachedGroupsCount: 5,
    riskLevel: "Low",
    prayerPoints: ["Personal spiritual vitality.", "Arctic remote missions.", "Secular culture help."],
    historicalContext: "Nordic nation with rich mission-history now largely secular."
  },
  {
    id: "om",
    name: "Oman",
    flag: "🇴🇲",
    population: 5100000,
    religion: "Islam",
    christianPercentage: 3,
    unreachedPercentage: 95,
    unreachedGroupsCount: 14,
    riskLevel: "Moderate",
    prayerPoints: ["Reaching the Ibadis.", "Expat church maturity.", "Seekers."],
    historicalContext: "Stable Gulf sultanate with a moderate Islamic approach."
  },
  {
    id: "pk",
    name: "Pakistan",
    flag: "🇵🇰",
    population: 220000000,
    religion: "Islam",
    christianPercentage: 1.5,
    unreachedPercentage: 98,
    unreachedGroupsCount: 420,
    riskLevel: "Extreme",
    prayerPoints: ["Blasphemy law protect.", "Slave brick-kiln believers.", "Unreached Baluch."],
    historicalContext: "Islamic republic with a resilient Christian minority facing extreme pressure."
  },
  {
    id: "pw",
    name: "Palau",
    flag: "🇵🇼",
    population: 18000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Faith in action.", "Youth leadership.", "Unity."],
    historicalContext: "Pacific archipelago with strong Christian influence."
  },
  {
    id: "pa",
    name: "Panama",
    flag: "🇵🇦",
    population: 4300000,
    religion: "Christianity",
    christianPercentage: 85,
    unreachedPercentage: 10,
    unreachedGroupsCount: 8,
    riskLevel: "Low",
    prayerPoints: ["Kuna and Embera people.", "Canal worker outreach.", "Family unity."],
    historicalContext: "Bridge between North and South America."
  },
  {
    id: "pg",
    name: "Papua New Guinea",
    flag: "🇵🇬",
    population: 9000000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 450,
    riskLevel: "High",
    prayerPoints: ["Tribal peace.", "Bible translation completion.", "Deepening discipleship."],
    historicalContext: "World's most linguistically diverse nation with high Christian percentage."
  },
  {
    id: "py",
    name: "Paraguay",
    flag: "🇵🇾",
    population: 7100000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 2,
    unreachedGroupsCount: 4,
    riskLevel: "Low",
    prayerPoints: ["Guarani outreach.", "Mennonite impact.", "Economic integrity."],
    historicalContext: "Landlocked South American nation with bilingual culture."
  },
  {
    id: "pe",
    name: "Peru",
    flag: "🇵🇪",
    population: 33000000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 2,
    unreachedGroupsCount: 15,
    riskLevel: "Moderate",
    prayerPoints: ["Quechua seekers.", "Andean village reach.", "Social justice."],
    historicalContext: "Inca heartland with established religious traditions."
  },
  {
    id: "ph",
    name: "Philippines",
    flag: "🇵🇭",
    population: 110000000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 10,
    unreachedGroupsCount: 35,
    riskLevel: "Moderate",
    prayerPoints: ["Southern Muslim Mindanao.", "Sending thousands out.", "Poor in slums."],
    historicalContext: "Major Christian hub in Asia with huge global migrant missionary impact."
  },
  {
    id: "pl",
    name: "Poland",
    flag: "🇵🇱",
    population: 38000000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 10,
    unreachedGroupsCount: 12,
    riskLevel: "Low",
    prayerPoints: ["Spiritual vibrancy.", "Youth reach.", "Ukrainian refugee care."],
    historicalContext: "Vibrant Catholic nation now seeing growth in evangelical circles."
  },
  {
    id: "pt",
    name: "Portugal",
    flag: "🇵🇹",
    population: 10200000,
    religion: "Christianity",
    christianPercentage: 80,
    unreachedPercentage: 15,
    unreachedGroupsCount: 12,
    riskLevel: "Low",
    prayerPoints: ["Gospel focus.", "University outreach.", "Migrant work."],
    historicalContext: "Nation that once led global maritime expansion and missions."
  },
  {
    id: "qa",
    name: "Qatar",
    flag: "🇶🇦",
    population: 2800000,
    religion: "Islam",
    christianPercentage: 10,
    unreachedPercentage: 85,
    unreachedGroupsCount: 8,
    riskLevel: "Moderate",
    prayerPoints: ["Migrant worker safety.", "Seeking locals.", "Christian presence impact."],
    historicalContext: "Wealthy peninsula with large foreign workforce."
  },
  {
    id: "ro",
    name: "Romania",
    flag: "🇷🇴",
    population: 19000000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 5,
    unreachedGroupsCount: 22,
    riskLevel: "Low",
    prayerPoints: ["Roma work expansion.", "Sending capacity.", "Biblical depth."],
    historicalContext: "Post-communist nation with strong evangelical presence."
  },
  {
    id: "ru",
    name: "Russia",
    flag: "🇷🇺",
    population: 146000000,
    religion: "Christianity",
    christianPercentage: 70,
    unreachedPercentage: 25,
    unreachedGroupsCount: 120,
    riskLevel: "High",
    prayerPoints: ["Freedom for smaller denominations.", "Caucasus unreached.", "Integrity."],
    historicalContext: "Vast nation with Orthodox history and diverse ethnic groups."
  },
  {
    id: "rw",
    name: "Rwanda",
    flag: "🇷🇼",
    population: 13000000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 2,
    unreachedGroupsCount: 3,
    riskLevel: "Low",
    prayerPoints: ["Trauma healing.", "Social transformation.", "Christian leadership."],
    historicalContext: "Nation miraculously unified and transformed after 1994 genocide."
  },
  {
    id: "kn",
    name: "Saint Kitts and Nevis",
    flag: "🇰🇳",
    population: 53000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 2,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Vibrant testimony.", "Youth leadership.", "Family strength."],
    historicalContext: "Caribbean twin-island federation."
  },
  {
    id: "lc",
    name: "Saint Lucia",
    flag: "🇱🇨",
    population: 180000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Biblical clarity.", "Youth outreach.", "Community unity."],
    historicalContext: "Island nation with rich French and British heritage."
  },
  {
    id: "vc",
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    population: 110000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Recovery from volcanoes.", "Faith resilience.", "Unity."],
    historicalContext: "Caribbean island chain with strong faith foundations."
  },
  {
    id: "ws",
    name: "Samoa",
    flag: "🇼🇸",
    population: 200000,
    religion: "Christianity",
    christianPercentage: 98,
    unreachedPercentage: 1,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Global mission mission.", "Family foundations.", "Biblical depth."],
    historicalContext: "Pacific nation with 'Samoa is founded on God' in its constitution."
  },
  {
    id: "sm",
    name: "San Marino",
    flag: "🇸🇲",
    population: 34000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 2,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Renewal.", "Youth witness.", "European relevance."],
    historicalContext: "World's oldest republic."
  },
  {
    id: "st",
    name: "Sao Tome and Principe",
    flag: "🇸🇹",
    population: 220000,
    religion: "Christianity",
    christianPercentage: 85,
    unreachedPercentage: 10,
    unreachedGroupsCount: 2,
    riskLevel: "Low",
    prayerPoints: ["Church health.", "Education.", "Social aid."],
    historicalContext: "Island nation off African coast."
  },
  {
    id: "sa",
    name: "Saudi Arabia",
    flag: "🇸🇦",
    population: 35000000,
    religion: "Islam",
    christianPercentage: 4,
    unreachedPercentage: 95,
    unreachedGroupsCount: 22,
    riskLevel: "Extreme",
    prayerPoints: ["Freedom for home groups.", "Seekers among native Saudis.", "Migrant believers' safety."],
    historicalContext: "The heart of the Islamic world, seeing quiet seeds sprout."
  },
  {
    id: "sn",
    name: "Senegal",
    flag: "🇸🇳",
    population: 16700000,
    religion: "Islam",
    christianPercentage: 5,
    unreachedPercentage: 90,
    unreachedGroupsCount: 38,
    riskLevel: "Moderate",
    prayerPoints: ["Outreach to the Wolof.", "Stable religious freedom.", "Village mission."],
    historicalContext: "Westernmost African nation with a tradition of religious tolerance."
  },
  {
    id: "rs",
    name: "Serbia",
    flag: "🇷🇸",
    population: 7000000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 10,
    unreachedGroupsCount: 15,
    riskLevel: "Low",
    prayerPoints: ["Healing from Balkan wars.", "Revival in cities.", "Integrity."],
    historicalContext: "Balkan country with deep Orthodox history."
  },
  {
    id: "sc",
    name: "Seychelles",
    flag: "🇸🇨",
    population: 98000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Spiritual depth.", "Social unity.", "Environment."],
    historicalContext: "Island archipelago with strong Catholic presence."
  },
  {
    id: "sl",
    name: "Sierra Leone",
    flag: "🇸🇱",
    population: 8000000,
    religion: "Islam/Christianity",
    christianPercentage: 20,
    unreachedPercentage: 60,
    unreachedGroupsCount: 18,
    riskLevel: "Moderate",
    prayerPoints: ["Recovery from civil war shadow.", "Discipleship focus.", "Education."],
    historicalContext: "West African nation with significant mineral wealth and spiritual needs."
  },
  {
    id: "sg",
    name: "Singapore",
    flag: "🇸🇬",
    population: 5800000,
    religion: "Christianity/Buddhism",
    christianPercentage: 18,
    unreachedPercentage: 40,
    unreachedGroupsCount: 25,
    riskLevel: "Low",
    prayerPoints: ["Missionary sending focus.", "Reaching domestic workers.", "Authentic faith."],
    historicalContext: "Global financial hub with a significant missionary-sending church."
  },
  {
    id: "sk",
    name: "Slovakia",
    flag: "🇸🇰",
    population: 5400000,
    religion: "Christianity",
    christianPercentage: 75,
    unreachedPercentage: 15,
    unreachedGroupsCount: 6,
    riskLevel: "Low",
    prayerPoints: ["Spiritual life beyond tradition.", "Youth reach.", "Roma ministry."],
    historicalContext: "Central European nation with strong Catholic identity."
  },
  {
    id: "si",
    name: "Slovenia",
    flag: "🇸🇮",
    population: 2100000,
    religion: "Christianity",
    christianPercentage: 70,
    unreachedPercentage: 25,
    unreachedGroupsCount: 4,
    riskLevel: "Low",
    prayerPoints: ["Personal faith.", "Evangelical witness growth.", "Revival."],
    historicalContext: "Scenic Alpine nation."
  },
  {
    id: "sb",
    name: "Solomon Islands",
    flag: "🇸🇧",
    population: 680000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 2,
    unreachedGroupsCount: 5,
    riskLevel: "Moderate",
    prayerPoints: ["Unity.", "Training leaders.", "Health."],
    historicalContext: "Diverse Pacific archipelago."
  },
  {
    id: "so",
    name: "Somalia",
    flag: "🇸🇴",
    population: 15900000,
    religion: "Islam",
    christianPercentage: 0.01,
    unreachedPercentage: 99.9,
    unreachedGroupsCount: 15,
    riskLevel: "Extreme",
    prayerPoints: ["Protection for few believers.", "Ending famine/war.", "Freedom to believe."],
    historicalContext: "One of the most dangerous nations in the world for Christians."
  },
  {
    id: "za",
    name: "South Africa",
    flag: "🇿🇦",
    population: 60000000,
    religion: "Christianity",
    christianPercentage: 80,
    unreachedPercentage: 15,
    unreachedGroupsCount: 45,
    riskLevel: "Moderate",
    prayerPoints: ["Healing from apartheid legacy.", "Crime/Violence solution.", "Sending missionaries north."],
    historicalContext: "The 'Rainbow Nation' with a massive but challenged church body."
  },
  {
    id: "ss",
    name: "South Sudan",
    flag: "🇸🇸",
    population: 11000000,
    religion: "Christianity/Animism",
    christianPercentage: 60,
    unreachedPercentage: 35,
    unreachedGroupsCount: 22,
    riskLevel: "Extreme",
    prayerPoints: ["Ending civil war.", "Refugee support.", "Discipleship in villages."],
    historicalContext: "World's newest nation, born out of decades of conflict."
  },
  {
    id: "es",
    name: "Spain",
    flag: "🇪🇸",
    population: 47000000,
    religion: "Christianity",
    christianPercentage: 70,
    unreachedPercentage: 25,
    unreachedGroupsCount: 35,
    riskLevel: "Low",
    prayerPoints: ["Breaking through secularism.", "Maghreb migrant reach.", "Revival in cities."],
    historicalContext: "Once the 'defender of the faith' now deeply post-Christian."
  },
  {
    id: "lk",
    name: "Sri Lanka",
    flag: "🇱🇰",
    population: 21000000,
    religion: "Buddhism/Hinduism",
    christianPercentage: 8,
    unreachedPercentage: 85,
    unreachedGroupsCount: 35,
    riskLevel: "High",
    prayerPoints: ["Peace between ethnicities.", "Buddhist outreach.", "Freedom for house churches."],
    historicalContext: "Island nation with rich cultural religious heritage."
  },
  {
    id: "sd",
    name: "Sudan",
    flag: "🇸🇩",
    population: 43800000,
    religion: "Islam",
    christianPercentage: 5,
    unreachedPercentage: 90,
    unreachedGroupsCount: 130,
    riskLevel: "Extreme",
    prayerPoints: ["Transition to freedom.", "Nuba Mountains believers.", "Darfur peace."],
    historicalContext: "North African nation seeing major political and spiritual shifts."
  },
  {
    id: "sr",
    name: "Suriname",
    flag: "🇸🇷",
    population: 580000,
    religion: "Christianity/Hinduism",
    christianPercentage: 50,
    unreachedPercentage: 35,
    unreachedGroupsCount: 8,
    riskLevel: "Low",
    prayerPoints: ["Unity in diversity.", "Interior tribes.", "Biblical depth."],
    historicalContext: "Diverse South American nation."
  },
  {
    id: "se",
    name: "Sweden",
    flag: "🇸🇪",
    population: 10300000,
    religion: "Irreligious/Christianity",
    christianPercentage: 60,
    unreachedPercentage: 35,
    unreachedGroupsCount: 22,
    riskLevel: "Low",
    prayerPoints: ["Revitalizing the state church.", "Immigrant missions.", "Secular targets."],
    historicalContext: "Modern, secular welfare state with significant mission history."
  },
  {
    id: "ch",
    name: "Switzerland",
    flag: "🇨🇭",
    population: 8600000,
    religion: "Christianity",
    christianPercentage: 70,
    unreachedPercentage: 25,
    unreachedGroupsCount: 15,
    riskLevel: "Low",
    prayerPoints: ["Spirit over wealth.", "Youth awakening.", "International missions."],
    historicalContext: "Center for the Reformation (Calvin/Zwingli) now neutral and secular."
  },
  {
    id: "sy",
    name: "Syria",
    flag: "🇸🇾",
    population: 17500000,
    religion: "Islam",
    christianPercentage: 8,
    unreachedPercentage: 90,
    unreachedGroupsCount: 28,
    riskLevel: "Extreme",
    prayerPoints: ["Restoration from war.", "Refugee seekers.", "Protection for remaining believers."],
    historicalContext: "Cradle of early Christianity now devastated by civil war."
  },
  {
    id: "tw",
    name: "Taiwan",
    flag: "🇹🇼",
    population: 23800000,
    religion: "Buddhism/Taoism",
    christianPercentage: 5,
    unreachedPercentage: 90,
    unreachedGroupsCount: 35,
    riskLevel: "Moderate",
    prayerPoints: ["Ancestral worship breakthrough.", "Youth outreach.", "Church unity."],
    historicalContext: "Island with strategic mission reach to the Chinese world."
  },
  {
    id: "tj",
    name: "Tajikistan",
    flag: "🇹🇯",
    population: 9500000,
    religion: "Islam",
    christianPercentage: 1,
    unreachedPercentage: 98,
    unreachedGroupsCount: 22,
    riskLevel: "High",
    prayerPoints: ["Freedom to share.", "Bible in local language.", "Youth vision."],
    historicalContext: "Mountainous Central Asian republic with strict controls."
  },
  {
    id: "tz",
    name: "Tanzania",
    flag: "🇹🇿",
    population: 60000000,
    religion: "Christianity/Islam",
    christianPercentage: 60,
    unreachedPercentage: 35,
    unreachedGroupsCount: 65,
    riskLevel: "Moderate",
    prayerPoints: ["Zanzibar outreach.", "Maasai missions.", "integrity in church."],
    historicalContext: "East African nation with peaceful religious co-existence."
  },
  {
    id: "th",
    name: "Thailand",
    flag: "🇹🇭",
    population: 70000000,
    religion: "Buddhism",
    christianPercentage: 1,
    unreachedPercentage: 98,
    unreachedGroupsCount: 95,
    riskLevel: "Low",
    prayerPoints: ["Breakthrough in Buddhist heartland.", "Village church plants.", "Hope in cities."],
    historicalContext: "The 'Land of Smiles' remains one of the world's most resilient unreached areas."
  },
  {
    id: "tl",
    name: "Timor-Leste",
    flag: "🇹🇱",
    population: 1300000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 5,
    unreachedGroupsCount: 8,
    riskLevel: "Moderate",
    prayerPoints: ["Biblical clarity.", "Youth training.", "Economic stability."],
    historicalContext: "Relatively new nation with deep Catholic roots."
  },
  {
    id: "tg",
    name: "Togo",
    flag: "🇹🇬",
    population: 8300000,
    religion: "Christianity/Indigenous",
    christianPercentage: 45,
    unreachedPercentage: 25,
    unreachedGroupsCount: 18,
    riskLevel: "Moderate",
    prayerPoints: ["Voodoo Strongholds freedom.", "Church planting.", "Training."],
    historicalContext: "West African nation with significant voodoo influence."
  },
  {
    id: "to",
    name: "Tonga",
    flag: "🇹🇴",
    population: 105000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 2,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Revival.", "Youth vision.", "Mission sending."],
    historicalContext: "Pacific kingdom with a 'Day of Sabbatical' legal structure."
  },
  {
    id: "tt",
    name: "Trinidad and Tobago",
    flag: "🇹🇹",
    population: 1400000,
    religion: "Christianity/Hinduism",
    christianPercentage: 55,
    unreachedPercentage: 40,
    unreachedGroupsCount: 12,
    riskLevel: "Low",
    prayerPoints: ["Unity in diversity.", "Urban ministry.", "Corruption help."],
    historicalContext: "Dual-island Caribbean nation."
  },
  {
    id: "tn",
    name: "Tunisia",
    flag: "🇹🇳",
    population: 11800000,
    religion: "Islam",
    christianPercentage: 0.1,
    unreachedPercentage: 99.8,
    unreachedGroupsCount: 10,
    riskLevel: "High",
    prayerPoints: ["Freedom for few believers.", "National peace.", "Seeking youth."],
    historicalContext: "Where the Arab Spring began, seeing a small house church grow."
  },
  {
    id: "tr",
    name: "Turkey",
    flag: "🇹🇷",
    population: 85000000,
    religion: "Islam",
    christianPercentage: 0.2,
    unreachedPercentage: 99,
    unreachedGroupsCount: 28,
    riskLevel: "Moderate",
    prayerPoints: ["Softening in cities.", "Unreached provinces.", "Bible schools."],
    historicalContext: "Cradle of the early church now a key unreached frontier."
  },
  {
    id: "tm",
    name: "Turkmenistan",
    flag: "🇹🇲",
    population: 6000000,
    religion: "Islam",
    christianPercentage: 0.5,
    unreachedPercentage: 99,
    unreachedGroupsCount: 12,
    riskLevel: "Extreme",
    prayerPoints: ["Safety for underground believers.", "Opening for Gospel.", "Water aid."],
    historicalContext: "Highly isolationist Central Asian state."
  },
  {
    id: "tv",
    name: "Tuvalu",
    flag: "🇹🇻",
    population: 11000,
    religion: "Christianity",
    christianPercentage: 95,
    unreachedPercentage: 2,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Spirit and climate resilience.", "Youth.", "Faith."],
    historicalContext: "One of the smallest and most vulnerable nations."
  },
  {
    id: "ug",
    name: "Uganda",
    flag: "🇺🇬",
    population: 45000000,
    religion: "Christianity",
    christianPercentage: 85,
    unreachedPercentage: 10,
    unreachedGroupsCount: 14,
    riskLevel: "Moderate",
    prayerPoints: ["Northern groups reach.", "Biblical integrity.", "Corruption fight."],
    historicalContext: "The 'Pearl of Africa' with a high christian population and growing zeal."
  },
  {
    id: "ua",
    name: "Ukraine",
    flag: "🇺🇦",
    population: 44000000,
    religion: "Christianity",
    christianPercentage: 80,
    unreachedPercentage: 15,
    unreachedGroupsCount: 22,
    riskLevel: "Extreme",
    prayerPoints: ["Protection and peace.", "Church as a house of refuge.", "Trauma healing."],
    historicalContext: "East European powerhouse of missionary training facing devastating conflict."
  },
  {
    id: "ae",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    population: 9900000,
    religion: "Islam",
    christianPercentage: 12,
    unreachedPercentage: 80,
    unreachedGroupsCount: 25,
    riskLevel: "Moderate",
    prayerPoints: ["Migrant churches.", "Seeking locals.", "Impact of Christians."],
    historicalContext: "High-tech desert nation with a global diverse workforce."
  },
  {
    id: "gb",
    name: "United Kingdom",
    flag: "🇬🇧",
    population: 67000000,
    religion: "Christianity/Irreligious",
    christianPercentage: 45,
    unreachedPercentage: 45,
    unreachedGroupsCount: 45,
    riskLevel: "Low",
    prayerPoints: ["Re-evangelizing the West.", "Church plants in council estates.", "Migrant zeal."],
    historicalContext: "The cradle of modern missions (Carey, Livingstone) now a mission field."
  },
  {
    id: "us",
    name: "United States",
    flag: "🇺🇸",
    population: 331000000,
    religion: "Christianity",
    christianPercentage: 65,
    unreachedPercentage: 25,
    unreachedGroupsCount: 120,
    riskLevel: "Low",
    prayerPoints: ["Renewal in secular cities.", "Sending capacity maintenance.", "Unity."],
    historicalContext: "The primary engine of global missions for a century, now facing challenges."
  },
  {
    id: "uy",
    name: "Uruguay",
    flag: "🇺🇾",
    population: 3500000,
    religion: "Irreligious/Christianity",
    christianPercentage: 45,
    unreachedPercentage: 50,
    unreachedGroupsCount: 4,
    riskLevel: "Low",
    prayerPoints: ["Breaking through secularism.", "Spiritual hunger.", "Youth."],
    historicalContext: "The most secular nation in Latin America."
  },
  {
    id: "uz",
    name: "Uzbekistan",
    flag: "🇺🇿",
    population: 34000000,
    religion: "Islam",
    christianPercentage: 1,
    unreachedPercentage: 98,
    unreachedGroupsCount: 45,
    riskLevel: "High",
    prayerPoints: ["Native church growth.", "Legal freedom.", "Bible access."],
    historicalContext: "Silk Road nation with a vibrant but restricted native church."
  },
  {
    id: "vu",
    name: "Vanuatu",
    flag: "🇻🇺",
    population: 300000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 12,
    riskLevel: "Low",
    prayerPoints: ["Village depth.", "Leadership training.", "Resilience."],
    historicalContext: "Pacific archipelago with many indigenous tribes."
  },
  {
    id: "ve",
    name: "Venezuela",
    flag: "🇻🇪",
    population: 28000000,
    religion: "Christianity",
    christianPercentage: 90,
    unreachedPercentage: 5,
    unreachedGroupsCount: 18,
    riskLevel: "Extreme",
    prayerPoints: ["Economic mercy.", "Church serving as lifeline.", "Exodus ministry."],
    historicalContext: "Nation in deep crisis where the church is a major source of hope."
  },
  {
    id: "vn",
    name: "Vietnam",
    flag: "🇻🇳",
    population: 97000000,
    religion: "Buddhism",
    christianPercentage: 9,
    unreachedPercentage: 80,
    unreachedGroupsCount: 75,
    riskLevel: "High",
    prayerPoints: ["Hmong/Montagnard churches.", "Opening for urban youth.", "Unity."],
    historicalContext: "Nation with significant evangelical growth among ethnic minorities."
  },
  {
    id: "ye",
    name: "Yemen",
    flag: "🇾🇪",
    population: 30000000,
    religion: "Islam",
    christianPercentage: 0.1,
    unreachedPercentage: 99.9,
    unreachedGroupsCount: 18,
    riskLevel: "Extreme",
    prayerPoints: ["Humanitarian aid with Gospel.", "Protection for few believers.", "End of war."],
    historicalContext: "Ancient biblical land facing one of the world's worst modern crises."
  },
  {
    id: "zm",
    name: "Zambia",
    flag: "🇿🇲",
    population: 18000000,
    religion: "Christianity",
    christianPercentage: 85,
    unreachedPercentage: 5,
    unreachedGroupsCount: 10,
    riskLevel: "Moderate",
    prayerPoints: ["Integrative discipleship.", "Outreach to few unreached.", "Integrity."],
    historicalContext: "A self-declared Christian nation in Southern Africa."
  },
  {
    id: "va",
    name: "Holy See (Vatican City)",
    flag: "🇻🇦",
    population: 800,
    religion: "Christianity",
    christianPercentage: 100,
    unreachedPercentage: 0,
    unreachedGroupsCount: 1,
    riskLevel: "Low",
    prayerPoints: ["Global influence.", "Wisdom for leadership.", "Spiritual renewal."],
    historicalContext: "The center of the Roman Catholic Church."
  },
  {
    id: "ps",
    name: "Palestine",
    flag: "🇵🇸",
    population: 5000000,
    religion: "Islam",
    christianPercentage: 1.5,
    unreachedPercentage: 98,
    unreachedGroupsCount: 8,
    riskLevel: "Extreme",
    prayerPoints: ["Peace and reconciliation.", "Freedom for local believers.", "Humanitarian aid."],
    historicalContext: "Region with deep biblical history and modern challenges."
  },
  {
    id: "xk",
    name: "Kosovo",
    flag: "🇽🇰",
    population: 1800000,
    religion: "Islam",
    christianPercentage: 3,
    unreachedPercentage: 95,
    unreachedGroupsCount: 5,
    riskLevel: "Moderate",
    prayerPoints: ["Ethnic reconciliation.", "Church growth.", "Economic stability."],
    historicalContext: "Youngest nation in the Balkans with complex status."
  },
  {
    id: "zw",
    name: "Zimbabwe",
    flag: "🇿🇼",
    population: 1500000,
    religion: "Christianity",
    christianPercentage: 80,
    unreachedPercentage: 10,
    unreachedGroupsCount: 12,
    riskLevel: "Moderate",
    prayerPoints: ["Economic restoration.", "Stable leadership.", "Mission zeal."],
    historicalContext: "Once breadbasket of Africa, now in need of spiritual and physical renewal."
  }
];


